### ISSUE TITLE
authornames failed display in <li> tag

### ISSUE THREAD

**Issue by ghost** [etinquis/etherpad-plugins#29]
Hi, authornames works fine with Etherpad 1.7.0 but failed with `<li>` tag.

**Comment by brunob** [comment]
+1 it fails alos if the text is indented with tabs :\

**Comment by JohnMcLear** [comment]
Fixed.  I don't have permission to publish to npm though..  @etinquis

**Comment by brunob** [comment]
(y) @JohnMcLear !

**Comment by etinquis** [comment]
@JohnMcLear What's your npm username?

**Comment by JohnMcLear** [comment]
Johnyma22

I assume you didn't get my email reply ;(

**Comment by etinquis** [comment]
No, I didn't get your reply, but you should be able to access the packages now.  Let me know if that's not the case.

**Comment by JohnMcLear** [comment]
published

**Comment by JohnMcLear** [comment]
tnx
